(source gnu)
(source melpa)

(depends-on "ace-window")
(depends-on "cask")
(depends-on "dash")
(depends-on "imenu-anywhere")
(depends-on "pallet")

(depends-on "ag")
(depends-on "counsel")
(depends-on "counsel-gtags")
(depends-on "counsel-projectile")
(depends-on "dumb-jump")
(depends-on "ggtags")
(depends-on "ivy")
(depends-on "ivy-rtags")
(depends-on "magit")
(depends-on "project")
(depends-on "projectile")
(depends-on "swiper")
(depends-on "undo-tree")
(depends-on "use-package")
(depends-on "which-key")
(depends-on "zenburn-theme")

(depends-on "exec-path-from-shell")
